// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOyy--Nrjq8-Pvk433e1sZJaQNeJZMoNE',
    appId: '1:2199232120:web:44342436654bcc516b578d',
    messagingSenderId: '2199232120',
    projectId: 'trashio-a5334',
    authDomain: 'trashio-a5334.firebaseapp.com',
    databaseURL: 'https://trashio-a5334-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trashio-a5334.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmkRI8EwkhqsloWd1sfKAO2IlgKqvQIo',
    appId: '1:2199232120:android:564f1cd0f6a7b51b6b578d',
    messagingSenderId: '2199232120',
    projectId: 'trashio-a5334',
    databaseURL: 'https://trashio-a5334-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trashio-a5334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP30DgOA6rCWt_cGOfXwiHUascg49DRVU',
    appId: '1:2199232120:ios:38a85e8d4bd29f006b578d',
    messagingSenderId: '2199232120',
    projectId: 'trashio-a5334',
    databaseURL: 'https://trashio-a5334-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trashio-a5334.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP30DgOA6rCWt_cGOfXwiHUascg49DRVU',
    appId: '1:2199232120:ios:38a85e8d4bd29f006b578d',
    messagingSenderId: '2199232120',
    projectId: 'trashio-a5334',
    databaseURL: 'https://trashio-a5334-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trashio-a5334.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOyy--Nrjq8-Pvk433e1sZJaQNeJZMoNE',
    appId: '1:2199232120:web:b3d98392c86610866b578d',
    messagingSenderId: '2199232120',
    projectId: 'trashio-a5334',
    authDomain: 'trashio-a5334.firebaseapp.com',
    databaseURL: 'https://trashio-a5334-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trashio-a5334.firebasestorage.app',
  );
}
